CREATE OR ALTER VIEW VKS1_PRODUTOS (INTERNCODE,NAME,SIMPLENAME,ACTIVED,BARCODE,UNIT,UPDATEAT)
AS

SELECT	 PRD.CODPROD					AS InternCode
		,PRD.DESCRICAO					AS Name
		,PRD.REDUZIDO					AS SimpleName
		,CASE	WHEN COALESCE(PRD.INATIVO, 'F') = 'F'
				THEN '0'
				ELSE '1' END			AS Actived
		,PRD.CODBARRA					AS BarCode
		,PRD.UNID_VAREJO				AS Unit
		,PRD.DATA						AS UpdateAt
FROM	 PRODUTO AS PRD;