
CREATE OR ALTER VIEW VKS1_CLIENTES (INTERCODE,CARDCODE,COMPANYNAME,TAXID1,TAXID2,SHIP_ADDRESS1,SHIP_ADDRESS2,SHIP_CITY,SHIP_UF,SHIP_BLOCK,SHIP_ZIPCODE,ACTIVATED,TRADINGNAME,CREATEDAT,PRICELIST,TRANSPORTERID,EMAIL,SALESMAN,ZONAFRANCA,UPDATEAT)
AS

SELECT
		 CLIFOR.CODIGO										AS InterCode
		,CLIFOR.OBSERVACAO									AS CardCode
	    ,CLIFOR.RAZSOCIAL									AS CompanyName
	    ,CASE	WHEN CLIFOR.PESSOAFJ = 'J'
	         	THEN CLIFOR.CNPJ
	          	ELSE CLIFOR.CPF END							AS TaxId1
	    ,CLIFOR.RGIE										AS TaxId2	
	    ,CLIFOR.ENDFAT || ', ' || CLIFOR.NRENDFAT 			AS Ship_Address1
	    ,CLIFOR.COMPLFAT									AS Ship_Address2
		,CLIFOR.CIDADEFAT									AS Ship_City 
		,CLIFOR.UFFAT										AS Ship_UF
	    ,CLIFOR.BAIRROFAT									AS Ship_Block
	    ,CLIFOR.CEPFAT										AS Ship_ZipCode
	    ,CASE	WHEN COALESCE(CLIFOR.INATIVO, 'F') = 'F'
	            THEN '0'
	            ELSE '1' END 								AS Activated
	 	,CLIFOR.FANTASIA									AS TradingName
		,CLIFOR.DTCAD										AS CreatedAt     
	    ,COALESCE(CLIFOR.TABELAPRECO,-1)					AS PriceList
	 	,COALESCE(CLIFOR.TRANSPORTADORA,0)					AS TransporterId
	    ,CLIFOR.EMAIL										AS Email
	    ,COALESCE(CLIFOR.VENDEDOR,0)						AS Salesman
	    ,CASE	WHEN COALESCE(CLIFOR.ZONAFRANCA, 'F') = 'F'
	            THEN '0'
	            ELSE '1' END 								AS ZonaFranca
	    ,CLIFOR.DTHR_ALTERACAO								AS UpdateAt
FROM 	 CLIFOR