CREATE OR ALTER VIEW VKS1_LISTAPRECO (PRICELIST,INTERNCODE,NAME,BARCODE,PRICE,UPDATEAT)
AS

SELECT	 PL.CODTABELA			AS PriceList
		,PR.CODPROD				AS InternCode
		,CT.DESCRICAO			AS Name
		,PR.CODBARRA			AS Barcode
		,PL.PRECOVAR			AS Price
		,PL.DATA				AS UpdateAt
FROM	 SPKS1_PRICELIST		AS PL
INNER JOIN PRODUTO				AS PR
	ON	 PL.CODBARRA = PR.CODBARRA
INNER JOIN CTAB					AS CT
	ON	 PL.CODTABELA = CT.CODIGO